import { useState } from "react";
import { AuthGate } from "@/components/AuthGate";
import { PanelShell } from "@/components/layout/PanelShell";

const THEMES = [
  { id: "thought-leadership", label: "Thought Leadership", icon: "💡", color: "#D4A853" },
  { id: "case-study", label: "Case Study", icon: "📊", color: "#3B82F6" },
  { id: "industry-insight", label: "Industry Insight", icon: "🔍", color: "#22C55E" },
  { id: "team-culture", label: "Team Culture", icon: "👥", color: "#A78BFA" },
  { id: "product-update", label: "Product Update", icon: "🚀", color: "#06B6D4" },
  { id: "market-analysis", label: "Market Analysis", icon: "📈", color: "#F59E0B" },
];

const TONES = [
  { id: "professional", label: "Professional" },
  { id: "inspiring", label: "Inspiring" },
  { id: "educational", label: "Educational" },
  { id: "provocative", label: "Provocative" },
];

const FORMATS = [
  { id: "short-post", label: "Short Post" },
  { id: "long-post", label: "Long Post" },
  { id: "carousel", label: "Carousel Outline" },
  { id: "article", label: "Article" },
  { id: "poll", label: "Poll" },
];

interface GeneratedPost {
  id: string;
  theme: string;
  tone: string;
  format: string;
  topic: string;
  content: string;
  created_at: string;
}

const SEED_HISTORY: GeneratedPost[] = [
  {
    id: "h1", theme: "Thought Leadership", tone: "Professional", format: "Long Post",
    topic: "Why African startups need local consulting firms",
    content: "I've spent the last 5 years consulting for African startups, and there's one thing I've learned:\n\nLocal context matters more than global frameworks.\n\nHere's why:\n\n1. Regulatory complexity varies by country\n2. Payment infrastructure is unique\n3. Cultural nuances affect product-market fit\n4. Talent markets differ drastically\n5. Partnership networks are relationship-driven\n\nThe best strategies are built from the ground up, not imported from Silicon Valley.\n\n#AfricaTech #Consulting #Strateis",
    created_at: "2026-04-09T14:00:00Z",
  },
  {
    id: "h2", theme: "Market Analysis", tone: "Educational", format: "Short Post",
    topic: "WAEMU fintech landscape 2026",
    content: "The WAEMU fintech market reached $2.3B in transaction volume in Q1 2026.\n\nKey drivers:\n- Mobile money penetration at 45%\n- BCEAO regulatory framework maturing\n- Wave disrupting Orange Money's dominance\n\nThe opportunity is massive. The question is: who will capture it?\n\n#WAEMU #Fintech #Africa",
    created_at: "2026-04-07T10:00:00Z",
  },
];

function ContentPageContent() {
  const [theme, setTheme] = useState(THEMES[0].id);
  const [tone, setTone] = useState(TONES[0].id);
  const [format, setFormat] = useState(FORMATS[0].id);
  const [topic, setTopic] = useState("");
  const [generating, setGenerating] = useState(false);
  const [preview, setPreview] = useState("");
  const [history] = useState<GeneratedPost[]>(SEED_HISTORY);

  function handleGenerate() {
    setGenerating(true);
    // Simulate generation (in V2: call Supabase Edge Function → Claude API)
    setTimeout(() => {
      setPreview(
        `[Generated ${FORMATS.find((f) => f.id === format)?.label} — ${THEMES.find((t) => t.id === theme)?.label}]\n\n` +
        `Topic: ${topic || "African business ecosystem"}\n` +
        `Tone: ${TONES.find((t) => t.id === tone)?.label}\n\n` +
        `--- Preview content would be generated by Claude API ---\n\n` +
        `Connect your ANTHROPIC_API_KEY in Supabase Edge Functions to enable real generation.`
      );
      setGenerating(false);
    }, 1500);
  }

  function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text);
  }

  return (
    <div className="grid gap-1.5" style={{ padding: "6px 8px", gridTemplateColumns: "1fr 1.2fr", gridTemplateRows: "auto 1fr", gridTemplateAreas: `"form preview" "form history"` }}>
      {/* Form */}
      <div style={{ gridArea: "form" }}>
        <PanelShell title="Content Generator" icon="✍️">
          <div className="p-3 space-y-3">
            {/* Theme selector */}
            <div>
              <label className="font-mono text-[8px] text-text-dim uppercase tracking-[0.1em] block mb-1.5">Theme</label>
              <div className="grid grid-cols-3 gap-1">
                {THEMES.map((t) => (
                  <button
                    key={t.id}
                    onClick={() => setTheme(t.id)}
                    className={`flex items-center gap-1.5 px-2 py-1.5 rounded border text-left transition-all ${
                      theme === t.id
                        ? "border-gold/40 bg-gold/[0.07]"
                        : "border-border-subtle hover:border-border hover:bg-bg-hover"
                    }`}
                  >
                    <span className="text-xs">{t.icon}</span>
                    <span className="font-mono text-[8px] text-text truncate">{t.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Tone */}
            <div>
              <label className="font-mono text-[8px] text-text-dim uppercase tracking-[0.1em] block mb-1.5">Tone</label>
              <div className="flex gap-1">
                {TONES.map((t) => (
                  <button
                    key={t.id}
                    onClick={() => setTone(t.id)}
                    className={`flex-1 px-2 py-1.5 rounded border font-mono text-[8px] font-bold uppercase tracking-wider transition-all ${
                      tone === t.id
                        ? "border-gold/40 bg-gold/[0.07] text-gold"
                        : "border-border-subtle text-text-dim hover:border-border"
                    }`}
                  >
                    {t.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Format */}
            <div>
              <label className="font-mono text-[8px] text-text-dim uppercase tracking-[0.1em] block mb-1.5">Format</label>
              <div className="flex gap-1 flex-wrap">
                {FORMATS.map((f) => (
                  <button
                    key={f.id}
                    onClick={() => setFormat(f.id)}
                    className={`px-2 py-1.5 rounded border font-mono text-[8px] font-bold uppercase tracking-wider transition-all ${
                      format === f.id
                        ? "border-gold/40 bg-gold/[0.07] text-gold"
                        : "border-border-subtle text-text-dim hover:border-border"
                    }`}
                  >
                    {f.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Topic */}
            <div>
              <label className="font-mono text-[8px] text-text-dim uppercase tracking-[0.1em] block mb-1.5">Topic</label>
              <textarea
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="Describe the topic for your content..."
                rows={3}
                className="w-full bg-bg-card border border-border rounded px-3 py-2 text-[11px] text-text font-sans outline-none focus:border-gold/50 transition-colors resize-none"
              />
            </div>

            {/* Generate button */}
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="w-full py-2.5 rounded font-mono text-[10px] font-bold uppercase tracking-wider text-bg-deep transition-all disabled:opacity-50"
              style={{ background: "linear-gradient(135deg, #D4A853, #C5952A)", boxShadow: "0 0 8px rgba(212,168,83,0.2)" }}
            >
              {generating ? "Generating..." : "Generate Content"}
            </button>
          </div>
        </PanelShell>
      </div>

      {/* Preview */}
      <div style={{ gridArea: "preview" }}>
        <PanelShell title="Preview" icon="👁️">
          <div className="p-3">
            {preview ? (
              <>
                <pre className="font-sans text-[11px] text-text whitespace-pre-wrap leading-relaxed">{preview}</pre>
                <button
                  onClick={() => copyToClipboard(preview)}
                  className="mt-3 px-3 py-1.5 rounded bg-bg-card border border-border font-mono text-[8px] font-bold uppercase tracking-wider text-gold hover:bg-bg-hover transition-colors"
                >
                  Copy to Clipboard
                </button>
              </>
            ) : (
              <div className="flex items-center justify-center h-32">
                <span className="font-mono text-[10px] text-text-muted uppercase tracking-wider">
                  Select options and generate content
                </span>
              </div>
            )}
          </div>
        </PanelShell>
      </div>

      {/* History */}
      <div style={{ gridArea: "history" }}>
        <PanelShell title="History" icon="📜" count={history.length}>
          <div className="overflow-y-auto max-h-[300px]">
            {history.map((post) => (
              <div key={post.id} className="px-3 py-2.5 border-b border-border-subtle hover:bg-bg-hover transition-colors">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-[8px] font-bold text-gold uppercase">{post.theme}</span>
                  <span className="font-mono text-[8px] text-text-dim">{post.tone}</span>
                  <span className="font-mono text-[8px] text-text-muted ml-auto">
                    {new Date(post.created_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })}
                  </span>
                </div>
                <p className="font-sans text-[11px] text-text mt-1 line-clamp-2">{post.content}</p>
                <button
                  onClick={() => copyToClipboard(post.content)}
                  className="font-mono text-[8px] text-gold mt-1 hover:underline"
                >
                  COPY
                </button>
              </div>
            ))}
          </div>
        </PanelShell>
      </div>
    </div>
  );
}

export function ContentPage() {
  return (
    <AuthGate>
      <ContentPageContent />
    </AuthGate>
  );
}
